apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 5
  selector:
    matchLabels:
      app: demo


  template:
    spec:
      containers:
      - name: demo
        image: demo:2.0
