apiVersion: batch/v1
kind: Job
metadata:
  name: cleanup
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: cleaner
        image: alpine:3.19
        command: ["sh", "-c", "echo cleaning && sleep 10"]
